/**
 * Largest US cities, in descending population order as supplied.
 *
 * Kept verbatim from the source list so an updated list can be pasted in and
 * diffed cleanly. Some names repeat because they name distinct cities in
 * different states (Arlington TX/VA, Columbus OH/GA, Glendale AZ/CA, Aurora
 * CO/IL, Kansas City MO/KS, Springfield MO/MA). There is no state field to
 * tell them apart, so `CITIES` below collapses them.
 */
const CITY_NAMES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "San Antonio",
  "Philadelphia",
  "San Diego",
  "Dallas",
  "Fort Worth",
  "Jacksonville",
  "Austin",
  "San Jose",
  "Charlotte",
  "Columbus-OH",
  "Indianapolis",
  "San Francisco",
  "Hempstead",
  "Seattle",
  "Denver",
  "Oklahoma City",
  "Nashville",
  "Washington",
  "Las Vegas",
  "El Paso",
  "Boston",
  "Detroit",
  "Louisville",
  "Portland-OR",
  "Memphis",
  "Baltimore",
  "Milwaukee",
  "Fresno",
  "Albuquerque",
  "Tucson",
  "Sacramento",
  "Atlanta",
  "Kansas City",
  "Mesa",
  "Raleigh",
  "Miami",
  "Brookhaven",
  "Colorado Springs",
  "Omaha",
  "Virginia Beach",
  "Long Beach",
  "Oakland",
  "Minneapolis",
  "Bakersfield",
  "Tampa",
  "Tulsa",
  "Aurora-CO",
  "Arlington-TX",
  "Wichita",
  "Cleveland",
  "Henderson",
  "New Orleans",
  "Islip",
  "Honolulu",
  "Anaheim",
  "Orlando",
  "Lexington",
  "Newark",
  "Stockton",
  "Riverside",
  "Irvine",
  "Corpus Christi",
  "Santa Ana",
  "Cincinnati",
  "Greensboro",
  "Durham",
  "Pittsburgh",
  "St. Paul",
  "North Las Vegas",
  "Lincoln",
  "Jersey City",
  "Oyster Bay",
  "Plano",
  "Gilbert",
  "Madison",
  "Reno",
  "Anchorage",
  "Port St. Lucie",
  "Chandler",
  "Fort Wayne",
  "Lubbock",
  "Chula Vista",
  "Buffalo",
  "St. Louis",
  "Laredo",
  "St. Petersburg",
  "Glendale-AZ",
  "Toledo",
  "Enterprise",
  "Winston-Salem",
  "Irving",
  "Chesapeake",
  "Garland",
  "Cape Coral",
  "Frisco",
  "Scottsdale",
  "McKinney",
  "Arlington-VA",
  "North Hempstead",
  "Richmond-VA",
  "Boise City",
  "Huntsville",
  "Hialeah",
  "Tacoma",
  "Spokane",
  "Spring Valley",
  "Norfolk",
  "Santa Clarita",
  "Fremont",
  "Fontana",
  "Salt Lake City",
  "San Bernardino",
  "Baton Rouge",
  "Modesto",
  "Babylon",
  "Sioux Falls",
  "Worcester",
  "Moreno Valley",
  "Yonkers",
  "Grand Prairie",
  "Des Moines",
  "Fayetteville",
  "Little Rock",
  "Tallahassee",
  "Huntington",
  "Amarillo",
  "Rochester-NY",
  "Overland Park",
  "Knoxville",
  "Peoria",
  "Augusta",
  "Vancouver",
  "Grand Rapids",
  "Sunrise Manor",
  "Columbus-GA",
  "Mobile",
  "Oxnard",
  "Chattanooga",
  "Providence",
  "Birmingham",
  "Brownsville",
  "Montgomery",
  "Clarksville",
  "Tempe",
  "Fort Lauderdale",
  "Huntington Beach",
  "Ontario",
  "Akron",
  "Elk Grove",
  "Cary",
  "Glendale-CA",
  "Salem-OR",
  "Newport News",
  "Aurora-IL",
  "Surprise",
  "Santa Rosa",
  "Eugene",
  "Rancho Cucamonga",
  "Pembroke Pines",
  "Paradise",
  "Denton",
  "Murfreesboro",
  "Shreveport",
  "Fort Collins",
  "Roseville",
  "Garden Grove",
  "Springfield-MO",
  "Oceanside",
  "Lancaster",
  "Killeen",
  "Ramapo",
  "Corona",
  "Paterson",
  "Charleston-SC",
  "Alexandria",
  "Palmdale",
  "Salinas",
  "Hollywood",
  "Kansas City-KS",
  "Macon-Bibb County",
  "Lakewood",
  "Sunnyvale",
  "Hayward",
  "Springfield-MA",
  "Bellevue",
  "Naperville",
  "Palm Bay",
  "Bridgeport",
  "Joliet",
  "McAllen",
  "Olathe",
  "Mesquite",
  "Midland",
  "Savannah",
  "Gainesville",
  "Waco",
] as const;

/**
 * Unique city names, first occurrence wins so population order is preserved.
 * Use this for select/combobox options — duplicates would produce repeated
 * options and colliding React keys.
 */
export const CITIES: readonly string[] = [...new Set(CITY_NAMES)];
